services:
  questions_app_db:
    image: postgres:14
    container_name: questions_app_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - questions_app_db:/var/lib/postgresql/data

volumes:
  questions_app_db:
