services:
  questions_app_db:
    image: mysql:8
    container_name: questions_app_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - questions_app_db:/var/lib/mysql

volumes:
  questions_app_db:      
